"""empty message

Revision ID: 9dce3816adfc
Revises: 1f2a31b5988a
Create Date: 2024-04-30 02:00:01.156000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dce3816adfc'
down_revision = '1f2a31b5988a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('fullname', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['fullname'])
        batch_op.create_unique_constraint(None, ['password'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('fullname')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
